import type {RichBlockMeta} from './blockMeta.js';
import {legacyRichTextCrdtPlugins} from './editorCrdtConfig.js';
import {
    basicMarksPlugin,
    codeMermaidPlugin,
    calloutsPlugin,
    codePlugin,
    codeVegaPlugin,
    columnsPlugin,
    headingsPlugin,
    imagesPlugin,
    inlineDatePlugin,
    ingredientsPlugin,
    legacyRichTextBlocksPlugin,
    legacyRichTextUiPlugin,
    linkPreviewPlugin,
    linksPlugin,
    listsPlugin,
    mathPlugin,
    quotePlugin,
    slidesPlugin,
    todosPlugin,
    type BlockEditorPlugin,
} from './plugins/index.js';

export const defaultBlockEditorPlugins: readonly BlockEditorPlugin<RichBlockMeta>[] = [
    basicMarksPlugin,
    calloutsPlugin,
    codePlugin,
    codeMermaidPlugin,
    codeVegaPlugin,
    columnsPlugin,
    headingsPlugin,
    imagesPlugin,
    inlineDatePlugin,
    ingredientsPlugin,
    legacyRichTextBlocksPlugin,
    legacyRichTextUiPlugin,
    linkPreviewPlugin,
    linksPlugin,
    listsPlugin,
    mathPlugin,
    quotePlugin,
    slidesPlugin,
    todosPlugin,
    ...legacyRichTextCrdtPlugins,
];
